version: '3.8'

services:
  produto-service:
    image: produto-service-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - produto-network
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: produto-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    networks:
      - produto-network
    volumes:
      - produto-db-data:/var/opt/mssql

networks:
  produto-network:
    driver: bridge

volumes:
  produto-db-data:
    driver: local
